// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuxwdiiordeewrhxwskg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1eHdkaWlvcmRlZXdyaHh3c2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MDE2MjIsImV4cCI6MjA1MDM3NzYyMn0.JsDa6As-ab46EmAetWZGefyr8FzjG19wbYDhMIzi5d4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);